# 端口号和项目根路径
server:
  port: 8018
  servlet:
    context-path: /initblog
# 编码设置
spring:
  http:
    encoding:
      charset: UTF-8
  # 数据库和连接池配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # url: 数据库URL 
    # username: 用户名
    # password: 密码
  # 邮件配置
  mail:
    # username: 邮箱名
    # password: 密码
    # host: 
    properties.mail.smtp.ssl.enable: true
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  # 配置 Redis
  redis:
    host: 127.0.0.1
    # port: Reids 端口
    # password: 密码
  # 配置 Elasticsearch
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300


# MyBatis Mapper配置文件
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.zhou.init.pojo

#  configuration:
#    use-generated-keys: true

# JSON 格式化时间
#jsckson:
#  time-zone: GMT+8
#  date-format: yyyy-MM-dd HH:mm:ss

aliyun:
  # 对象存储
  oss:
    # endpoint: 地域
    # accessKeyId: key
    # accessKeySecret: pwd
    # bucketName: name


# Redis配置
#redis:
#  hostName: 127.0.0.1
#  port: 6379
#  password: 123
#  maxIdle: 5
#  maxActive: 10
#  maxTotal: 10
#  maxWaitMillis: 1000
#  minEvictableIdleTimeMillis: 300000
#  numTestsPerEvictionRun: 1024
#  timeBetweenEvictionRunsMillis: 30000
#  testOnBorrow: false
#  testWhileIdle: false


logging:
  level:
    com.zhou.init.mapper: debug
    com:
      zhou:
        init:
          controller: debug




